name: Build Apps

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        build:
          - platform: linux/amd64
            os: ubuntu-latest
          - platform: windows/amd64
            os: windows-latest
          - platform: darwin/arm64
            os: macos-latest

    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Checkout codes
        uses: actions/checkout@v6
        with:
          submodules: recursive

      #- name: Setup Go
      #  uses: actions/setup-go@v6
      #  with:
      #    go-version-file: "go.mod"

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          package_json_file: frontend/package.json
          run_install: false

      #- name: Setup Node.js
      #  uses: actions/setup-node@v6
      #  with:
      #    node-version: lts/*
      #    cache: pnpm
      #    cache-dependency-path: frontend

      - uses: dAppServer/wails-build-action@main
        with:
          build-name: Zashboard
          build-platform: ${{ matrix.build.platform }}
          build-obfuscate: true
